language: 
  - rust
  - node_js

jobs:
  include:
  - stage: "rust"
    - language: rust
      rust: stable
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      # cache: cargo
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        # - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
        - cargo install-update -a
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - cargo test --verbose
        - cargo build --verbose
        - wasm-pack test --chrome --headless
        - wasm-pack build
  - stage: "js"
    - language: node_js
      node_js: node
      # cache: npm
      script:
        - npm install
        - npm run test
        - npm run-script build
