# language: 
#   rust
#   node_js

sudo: false

cache: 
  cargo
  npm

matrix:
  include:
  # Builds with wasm-pack.
  - language: rust
      rust: stable
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - cargo install-update -a
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      install:
        - npm install
      script:
        - cargo test --verbose
        - cargo build --verbose
        - wasm-pack test --chrome --headless
        - wasm-pack build

  - language: node.js
      node_js: 
        - 'node'
      script:
        - npm install
        - npm run test

