name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install packages
      run: (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      run: cargo install-update -a
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - name: Build
      env: RUST_BACKTRACE=1
      run: cargo test --verbose
      run: cargo build --verbose
    - name: Install wasm-pack
      run: wasm-pack test --chrome --headless
      run: wasm-pack build
    - name: Node.js CI
      run: npm install
      run: npm run test
      run: npm run-script build